#!/bin/bash

#SBATCH --account=tra24_IngInfBo
#SBATCH --partition=g100_usr_prod

#SBATCH -t 00:05:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1  # Run a single task per node, more explicit than '-n 1'
#SBATCH -c 48                #  number of CPU cores i.e. OpenMP threads per task
#SBATCH -o job.out
#SBATCH -e job.err


srun ./sommavet 48
